### ISSUE TITLE
Docs: CREATE_BOT.md Image Not Displaying

### ISSUE THREAD

**Issue by 0xVikasRushi** [0xVikasRushi/OpenIssueMonitor#2]
### Current Image Display:

![Screenshot 2023-10-13 at 5:51:37 PM](https://github.com/0xVikasRushi/OpenIssueMonitor/assets/88543171/4a3aff79-81bf-41c0-8794-0568d446d180)

### Requested Changes:

Please replace the existing images with the following [screenshots](https://drive.google.com/drive/u/1/folders/1thJwjg6sdFfsGlLdTnarU8Bo0BP-JmEc) in [CREATE_BOT.md](https://github.com/0xVikasRushi/OpenIssueMonitor/blob/main/CREATE_BOT.md). Additionally, adjust the size of the new screenshots as needed for proper display.

**Comment by AmosBlack** [comment]
Hey, give access to amosblxckk@gmail.com for the screenshots, thx.

**Comment by 0xVikasRushi** [comment]
@AmosBlack Thanks for your interest. Given access to Everyone

**Comment by AmosBlack** [comment]
Fixed this issue in a new [PR](https://github.com/0xVikasRushi/OpenIssueMonitor/pull/7) I just created.
