### ISSUE TITLE
Docs : Add Labels to README

### ISSUE THREAD

**Issue by 0xVikasRushi** [0xVikasRushi/OpenIssueMonitor#3]
Include the following labels in the README file:

1. Version
2. License 
3. Stars
4. Open Issues
5. Pull requests
6. Last Commit 

Example:
![Screenshot 2023-10-13 at 7 56 31 PM](https://github.com/0xVikasRushi/OpenIssueMonitor/assets/88543171/d837b32f-8fa5-4845-ab89-51fac13d498d)

Refer this [example-readme](https://github.com/0xVikasRushi/ipfs-encrypt#readme)

**Comment by Freakyab** [comment]
assign me

**Comment by Freakyab** [comment]
can you please assign it to me.
